### ISSUE TITLE
Cannot parse patches that contain preprocessing selectors

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-verify#27]
The `# [linux]` selector in this example:
```
source:
  url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fcf.patch           # [linux]
```
leads to:
```
Traceback (most recent call last):
  File ".../bin/conda-verify", line 11, in <module>
    load_entry_point('conda-verify==3.0.0', 'console_scripts', 'conda-verify')()
  File ".../lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python3.6/site-packages/conda_verify/cli.py", line 35, in cli
    checks_to_ignore=ignore, exit_on_error=exit)
  File ".../lib/python3.6/site-packages/conda_verify/verify.py", line 67, in verify_recipe
    in dir(recipe_check) if method.startswith('check') and
  File ".../lib/python3.6/site-packages/conda_verify/verify.py", line 68, in <listcomp>
    getattr(recipe_check, method)() is not None]
  File ".../lib/python3.6/site-packages/conda_verify/checks.py", line 470, in check_for_valid_files
    source_patches.extend(source.get('patches', []))
TypeError: 'NoneType' object is not iterable
```

**Comment by msarahan** [comment]
Thanks for the many bug reports.  Just so you're aware, we have attempted to revive conda-verify mainly to help isolate an issue where 32-bit win packages were containing 64-bit executables.  Conda-verify remains a relatively low priority project in the short term.  If you actually want to see things changed or fixed quickly, it will be much more effective to submit PR's rather than issues.

**Comment by mandeep** [comment]
@sscherfke I am unable to reproduce this with the snippet you provided. Could you show me the full meta.yaml file?

**Comment by sscherfke** [comment]
Hm, it seems to work with 3.0.1.  Maybe the issue has been fixed by accident.
